# Generated by Django 6.0.5 on 2026-06-01 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_payment_stripe_price_id_payment_stripe_product_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="stripe_price_id",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="stripe_product_id",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="stripe_session_id",
            field=models.TextField(blank=True, null=True),
        ),
    ]
